name: Trigger OpenMV Studio Resources Update

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: openmv-studio

      - name: Trigger resources workflow
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh workflow run resources.yml --repo ${{ github.repository_owner }}/openmv-studio
